import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  English: {
    home: 'Home',
    services: 'Services',
    about: 'About',
    contact: 'Contact',
    help: 'Help',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    dashboard: 'Dashboard',
    myBookings: 'My Bookings',
    workerPortal: 'ODF for Job',
    availableWorkers: 'Available Workers',
    noWorkers: 'No available workers found',
    sendRequest: 'Send Booking Request',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    completed: 'Completed',
    cancelled: 'Cancelled',
    payNow: 'Pay Now',
    cashOnService: 'Cash on Service',
    payBefore: 'Pay Before',
    total: 'Total',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Something went wrong',
    back: 'Back',
  },
  Hindi: {
    home: 'होम',
    services: 'सेवाएं',
    about: 'हमारे बारे में',
    contact: 'संपर्क',
    help: 'सहायता',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    dashboard: 'डैशबोर्ड',
    myBookings: 'मेरी बुकिंग',
    workerPortal: 'ओडीएफ जॉब के लिए',
    availableWorkers: 'उपलब्ध कामगार',
    noWorkers: 'कोई कामगार उपलब्ध नहीं',
    sendRequest: 'बुकिंग अनुरोध भेजें',
    pending: 'लंबित',
    accepted: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    completed: 'पूर्ण',
    cancelled: 'रद्द',
    payNow: 'अभी भुगतान करें',
    cashOnService: 'सेवा पर नकद',
    payBefore: 'पहले भुगतान',
    total: 'कुल',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    edit: 'संपादित करें',
    loading: 'लोड हो रहा है...',
    error: 'कुछ गलत हो गया',
    back: 'वापस',
  },
  Marathi: {
    home: 'होम',
    services: 'सेवा',
    about: 'आमच्याबद्दल',
    contact: 'संपर्क',
    help: 'मदत',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    dashboard: 'डॅशबोर्ड',
    myBookings: 'माझी बुकिंग',
    workerPortal: 'ओडीएफ जॉबसाठी',
    availableWorkers: 'उपलब्ध कामगार',
    noWorkers: 'कोणताही कामगार उपलब्ध नाही',
    sendRequest: 'बुकिंग विनंती पाठवा',
    pending: 'प्रलंबित',
    accepted: 'स्वीकारलेले',
    rejected: 'नाकारलेले',
    completed: 'पूर्ण',
    cancelled: 'रद्द',
    payNow: 'आता पैसे द्या',
    cashOnService: 'सेवेवर रोख',
    payBefore: 'पूर्वी पैसे द्या',
    total: 'एकूण',
    submit: 'सबमिट',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    edit: 'संपादित करा',
    loading: 'लोड होत आहे...',
    error: 'काहीतरी चूक झाली',
    back: 'मागे',
  },
  Telugu: {
    home: 'హోమ్',
    services: 'సేవలు',
    about: 'మా గురించి',
    contact: 'సంప్రదించండి',
    help: 'సహాయం',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    dashboard: 'డాష్‌బోర్డ్',
    myBookings: 'నా బుకింగ్‌లు',
    workerPortal: 'ఓడిఎఫ్ జాబ్ కోసం',
    availableWorkers: 'అందుబాటులో ఉన్న కార్మికులు',
    noWorkers: 'అందుబాటులో కార్మికులు లేరు',
    sendRequest: 'బుకింగ్ అభ్యర్థన పంపండి',
    pending: 'పెండింగ్',
    accepted: 'ఆమోదించబడింది',
    rejected: 'తిరస్కరించబడింది',
    completed: 'పూర్తయింది',
    cancelled: 'రద్దు',
    payNow: 'ఇప్పుడు చెల్లించండి',
    cashOnService: 'సేవపై నగదు',
    payBefore: 'ముందుగా చెల్లించండి',
    total: 'మొత్తం',
    submit: 'సమర్పించండి',
    cancel: 'రద్దు',
    save: 'సేవ్',
    edit: 'సవరించండి',
    loading: 'లోడ్ అవుతోంది...',
    error: 'ఏదో తప్పు జరిగింది',
    back: 'వెనుక',
  },
  Tamil: {
    home: 'முகப்பு',
    services: 'சேவைகள்',
    about: 'எங்களை பற்றி',
    contact: 'தொடர்பு',
    help: 'உதவி',
    signIn: 'உள்நுழை',
    signOut: 'வெளியேறு',
    dashboard: 'டாஷ்போர்டு',
    myBookings: 'என் முன்பதிவுகள்',
    workerPortal: 'ஒடிஎஃப் வேலைக்கு',
    availableWorkers: 'கிடைக்கும் தொழிலாளர்கள்',
    noWorkers: 'கிடைக்கும் தொழிலாளர்கள் இல்லை',
    sendRequest: 'முன்பதிவு கோரிக்கை அனுப்பு',
    pending: 'நிலுவை',
    accepted: 'ஏற்றுக்கொள்ளப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    completed: 'முடிந்தது',
    cancelled: 'ரத்து',
    payNow: 'இப்போது செலுத்துங்கள்',
    cashOnService: 'சேவையில் பணம்',
    payBefore: 'முன்பு செலுத்துங்கள்',
    total: 'மொத்தம்',
    submit: 'சமர்ப்பி',
    cancel: 'ரத்து',
    save: 'சேமி',
    edit: 'திருத்து',
    loading: 'ஏற்றுகிறது...',
    error: 'ஏதோ தவறு நடந்தது',
    back: 'பின்செல்',
  },
  Malayalam: {
    home: 'ഹോം',
    services: 'സേവനങ്ങൾ',
    about: 'ഞങ്ങളെ കുറിച്ച്',
    contact: 'ബന്ധപ്പെടുക',
    help: 'സഹായം',
    signIn: 'സൈൻ ഇൻ',
    signOut: 'സൈൻ ഔട്ട്',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    myBookings: 'എന്റെ ബുക്കിംഗുകൾ',
    workerPortal: 'ഒഡിഎഫ് ജോലിക്ക്',
    availableWorkers: 'ലഭ്യമായ തൊഴിലാളികൾ',
    noWorkers: 'ലഭ്യമായ തൊഴിലാളികൾ ഇല്ല',
    sendRequest: 'ബുക്കിംഗ് അഭ്യർത്ഥന അയയ്ക്കുക',
    pending: 'തീർപ്പാകാത്ത',
    accepted: 'സ്വീകരിച്ചു',
    rejected: 'നിരസിച്ചു',
    completed: 'പൂർത്തിയായി',
    cancelled: 'റദ്ദാക്കി',
    payNow: 'ഇപ്പോൾ പണമടയ്ക്കുക',
    cashOnService: 'സേവനത്തിൽ പണം',
    payBefore: 'മുമ്പ് പണമടയ്ക്കുക',
    total: 'ആകെ',
    submit: 'സമർപ്പിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    save: 'സേവ് ചെയ്യുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    error: 'എന്തോ തെറ്റ് സംഭവിച്ചു',
    back: 'തിരികെ',
  },
  Gujarati: {
    home: 'હોમ',
    services: 'સેવાઓ',
    about: 'અમારા વિશે',
    contact: 'સંપર્ક',
    help: 'મદદ',
    signIn: 'સાઇન ઇન',
    signOut: 'સાઇન આઉટ',
    dashboard: 'ડેશબોર્ડ',
    myBookings: 'મારી બુકિંગ્સ',
    workerPortal: 'ઓડીએફ જોબ માટે',
    availableWorkers: 'ઉપલબ્ધ કામદારો',
    noWorkers: 'કોઈ કામદાર ઉપલબ્ધ નથી',
    sendRequest: 'બુકિંગ વિનંતી મોકલો',
    pending: 'બાકી',
    accepted: 'સ્વીકારેલ',
    rejected: 'નકારેલ',
    completed: 'પૂર્ણ',
    cancelled: 'રદ',
    payNow: 'હમણાં ચૂકવો',
    cashOnService: 'સેવા પર રોકડ',
    payBefore: 'પહેલાં ચૂકવો',
    total: 'કુલ',
    submit: 'સબમિટ',
    cancel: 'રદ',
    save: 'સાચવો',
    edit: 'ફેરફાર',
    loading: 'લોડ થઈ રહ્યું છે...',
    error: 'કંઈક ખોટું થયું',
    back: 'પાછળ',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('odforce-language') || 'English';
  });

  const handleSetLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('odforce-language', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.English[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
